### ISSUE TITLE
Error when re-starting che

### ISSUE THREAD

**Issue by slemeur** [che-incubator/chectl#82] opened 2019-04-15 09:40 UTC
I've been running che with chectl without troubles last week. Restarting it today raised an error:

```$ chectl server:start
  ✔ ✈️  Minikube preflight checklist
    ✔ Verify if kubectl is installed
    ✔ Verify if minikube is installed
    ✔ Verify if minikube is running
    ↓ Start minikube [skipped]
      → Minikube is already running.
    ✔ Verify userland-proxy is disabled...done.
    ✔ Verify if minikube ingress addon is enabled
    ↓ Enable minikube ingress addon [skipped]
      → Ingress addon is already enabled.
    ✔ Retrieving minikube IP and domain for ingress URLs...192.168.99.108.nip.io.
  ✔ 🏃‍  Running Helm to install Che
    ✔ Verify if helm is installed
    ✔ Create Tiller Role Binding...it already exist.
    ✔ Create Tiller Service Account...it already exist.
    ✔ Create Tiller RBAC
    ✔ Create Tiller Service...it already exist.
    ✔ Preparing Che Helm Chart...done.
    ✔ Updating Helm Chart dependencies...done.
    ✔ Deploying Che Helm Chart...done.
  ❯ ✅  Post installation checklist
    ❯ Che pod bootstrap
      ✖ scheduling
        → ERR_TIMEOUT
        downloading images
        starting
      Retrieving Che Server URL
      Che status check
Error: ERR_TIMEOUT
    at KubeHelper.<anonymous> (/snapshot/chectl/lib/api/kube.js:0:0)
    at Generator.next (<anonymous>)
    at fulfilled (/snapshot/chectl/node_modules/tslib/tslib.js:104:62)```


Note: When stopping che, I did `chectl server:stop`

**Comment by slemeur** [comment] 2019-04-15 09:45
After doing a `chectl server:delete` I've been able to restart che, but lost my workspaces.

**Comment by l0rd** [comment] 2019-04-15 15:07
I think that's a duplicate of #77

**Comment by benoitf** [comment] 2019-05-28 08:04
yes, duplicate of #77

**Closed by benoitf** 2019-05-28 08:04 UTC
