### ISSUE TITLE
Deployment of Che server is failed because of unbound PVC

### ISSUE THREAD

**Issue by Ohrimenko1988** [che-incubator/chectl#122] opened 2019-06-01 08:19 UTC
### Reproduction steps:
 - Download chectl (tag 20190529142525)
 - Start Kubernetes cluster on minikube cluster by command "minikube start --memory 10240 --cpus 4 --docker-opt userland-proxy=false"
 - Launch deploy command "./chectl-linux server:start", bug has been detected for the latest (13456) tag

**Expected result:**
Che server is deployed and available to use

**Observed behavior:**
Deployment is failed

**Notes:**
Deployment works with previous day che-server image (tag 13446)

**Attachments:**

Pod status:
![Screenshot from 2019-06-01 11-07-10](https://user-images.githubusercontent.com/22724619/58745811-c5b0c780-845e-11e9-8bb7-76e4b4693577.png)

Che server logs:
[logs-from-che-in-che-654b786456-nqbvz.txt](https://github.com/che-incubator/chectl/files/3243578/logs-from-che-in-che-654b786456-nqbvz.txt)

**Comment by dmytro-ndp** [comment] 2019-06-03 09:32
Issue caused by commit https://github.com/eclipse/che/commit/ee4461b2fd3e15c0c0b454d1b17e60f768025191
_Che7 E2E Happy Path Tests_ weren't run against those changes in [corresponding PR](https://github.com/eclipse/che/pull/13417).
Nightly _Che7 E2E Happy Path Tests_ log could be found [here](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che7-e2e-tests/job/CHE-7-selenium-ts-experimental/294/console).

**Comment by metlos** [comment] 2019-07-03 07:44
This is fixed in newer che images.

**Closed by metlos** 2019-07-03 07:44 UTC
