### ISSUE TITLE
Not able to start minikube on Mac

### ISSUE THREAD

**Issue by skabashnyuk** [che-incubator/chectl#15] opened 2018-12-11 07:44 UTC
I've tried to start a server and it stuck in starting state.
```
[ 9:38:23]sj:bin[master]#: ./run  server:start
  ✔ Verify if kubectl is installed
  ✔ Verify if minikube is installed
  ✔ Verify if helm is installed
  ✔ Verify if minikube is running
  ✖ Start minikube
    → Starting cluster components...
    Verify if minikube ingress addon is enabled
    Enable minikube ingress addon
    Verify if Tiller Role Binding exist
    Create Tiller Role Binding
    Verify if Tiller Service Account exists
    Create Tiller Service Account
    Create Tiller RBAC
    Verify if Tiller service exist
    Create Tiller Service
    Verify if namespace kube-che exist
    Verify if Che server is already running
    Deploy Che Server
    Waiting for Che Server to start and respond
    Retrieving Che Server URL
Error: Command failed: minikube start --memory=4096 --cpus=4 --disk-size=50g
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
    at makeError (~/dev/src/che-incubator/chectl/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (~/dev/src/che-incubator/chectl/node_modules/execa/index.js:278:16)
    at <anonymous>
```
However, at the same time, I was able to get minikube status
```
[ 9:30:47]sj:che[master]#: minikube status
minikube: Running
cluster: Running
kubectl: Correctly Configured: pointing to minikube-vm at 192.168.99.100
```
If I try to execute command one more time imidiatle after the fail I've got.
```
[ 9:41:28]sj:bin[master]#: ./run  server:start
  ✔ Verify if kubectl is installed
  ✔ Verify if minikube is installed
  ✔ Verify if helm is installed
  ✔ Verify if minikube is running
  ↓ Start minikube [skipped]
    → Minikube is already running.
  ✔ Verify if minikube ingress addon is enabled
  ↓ Enable minikube ingress addon [skipped]
    → Ingress addon is already enabled.
  ✔ Verify if Tiller Role Binding exist
  ✖ Create Tiller Role Binding
    → error: no matches for kind "ClusterRoleBinding" in version "rbac.authorization.k8s.io/v1beta1"
    Verify if Tiller Service Account exists
    Create Tiller Service Account
    Create Tiller RBAC
    Verify if Tiller service exist
    Create Tiller Service
    Verify if namespace kube-che exist
    Verify if Che server is already running
    Deploy Che Server
    Waiting for Che Server to start and respond
    Retrieving Che Server URL
Error: Command failed: kubectl create clusterrolebinding add-on-cluster-admin --clusterrole=cluster-admin --serviceaccount=kube-system:default
error: no matches for kind "ClusterRoleBinding" in version "rbac.authorization.k8s.io/v1beta1"
    at makeError (~/dev/src/che-incubator/chectl/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (~/dev/src/che-incubator/chectl/node_modules/execa/index.js:278:16)
    at <anonymous>
```

**Comment by l0rd** [comment] 2019-02-06 16:33
`Error parsing version semver:  Version string empty`

@skabashnyuk that's a minikube start error. minikube can't start on your machine. There is not much `chectl` can do for your. 

You can try resetting your minikube (`minikube stop && minikube delete && rm -rf ~/.minikube && rm -rf ~/.kube`), and start minikube manually with `minikube start --memory=4096 --cpus=4 --disk-size=50g`.

**Comment by skabashnyuk** [comment] 2019-02-06 20:10
I assume that is not an issue with starting minikube. Same story as I discrubed in issue header on a step two.

```
[18:05:34]sj:bin[master]#: minikube stop && minikube delete && rm -rf ~/.minikube && rm -rf ~/.kube
Stopping local Kubernetes cluster...
Machine stopped.
Deleting local Kubernetes cluster...
Machine deleted.
[22:01:06]sj:bin[master]#: minikube start --memory=4096 --cpus=4 --disk-size=50g
There is a newer version of minikube available (v0.33.1).  Download it here:
https://github.com/kubernetes/minikube/releases/tag/v0.33.1

To disable this notification, run the following:
minikube config set WantUpdateNotification false
Starting local Kubernetes v1.12.4 cluster...
Starting VM...
Downloading Minikube ISO
 178.88 MB / 178.88 MB [============================================] 100.00% 0s
Getting VM IP address...
Moving files into cluster...
Downloading kubeadm v1.12.4
Downloading kubelet v1.12.4
Finished Downloading kubeadm v1.12.4
Finished Downloading kubelet v1.12.4
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Stopping extra container runtimes...
Starting cluster components...
Verifying kubelet health ...
Verifying apiserver health ...Kubectl is now configured to use the cluster.
Loading cached images from config file.


Everything looks great. Please enjoy minikube!
[22:05:51]sj:bin[master]#: minikube status
host: Running
kubelet: Running
apiserver: Running
kubectl: Correctly Configured: pointing to minikube-vm at 192.168.99.100[22:06:01]sj:bin[master]#:
[22:06:03]sj:bin[master]#:
[22:06:03]sj:bin[master]#:
[22:06:03]sj:bin[master]#: DEBUG=* && ./run server:start
(node:20065) Error Plugin: chectl: could not find package.json with { type: 'core',
  root: '/Users/sj/dev/src/che-incubator/chectl',
  name: '@oclif/plugin-autocomplete' }
module: @oclif/config@1.9.0
task: loadPlugins
plugin: chectl
root: /Users/sj/dev/src/che-incubator/chectl
See more details with DEBUG=*
  ✔ Verify if kubectl is installed
  ✔ Verify if minikube is installed
  ✔ Verify if helm is installed
  ✔ Verify if minikube is running
  ↓ Start minikube [skipped]
    → Minikube is already running.
  ✔ Verify if minikube ingress addon is enabled
  ✔ Enable minikube ingress addon
  ✔ Verify if Tiller Role Binding exist
  ✔ Create Tiller Role Binding
  ✔ Verify if Tiller Service Account exists
  ✔ Create Tiller Service Account
  ✔ Create Tiller RBAC
  ✔ Verify if Tiller service exist
  ✖ Create Tiller Service
    → For more information on securing your installation see: https://docs.helm.sh/using_helm/#securing-your-helm-installation
    Verify if namespace kube-che exist
    Verify if Che server is already running
    Deploy Che Server
    Waiting for Che Server to start and respond
    Retrieving Che Server URL
Error: Command failed: helm init --service-account tiller --wait
$HELM_HOME has been configured at ~/.helm.
Tiller (the Helm server-side component) has been installed into your Kubernetes Cluster.
Please note: by default, Tiller is deployed with an insecure 'allow unauthenticated users' policy.
To prevent this, run `helm init` with the --tiller-tls-verify flag.
For more information on securing your installation see: https://docs.helm.sh/using_helm/#securing-your-helm-installation
    at makeError (~/dev/src/che-incubator/chectl/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (~/dev/src/che-incubator/chectl/node_modules/execa/index.js:278:16)
    at <anonymous>
```

**Comment by skabashnyuk** [comment] 2019-02-06 20:16
however the good news. On a third try I got.
```
[22:11:18]sj:bin[master]#: ./run server:start
(node:20180) Error Plugin: chectl: could not find package.json with { type: 'core',
  root: '/Users/sj/dev/src/che-incubator/chectl',
  name: '@oclif/plugin-autocomplete' }
module: @oclif/config@1.9.0
task: loadPlugins
plugin: chectl
root: /Users/sj/dev/src/che-incubator/chectl
See more details with DEBUG=*
  ✔ Verify if kubectl is installed
  ✔ Verify if minikube is installed
  ✔ Verify if helm is installed
  ✔ Verify if minikube is running
  ↓ Start minikube [skipped]
    → Minikube is already running.
  ✔ Verify if minikube ingress addon is enabled
  ↓ Enable minikube ingress addon [skipped]
    → Ingress addon is already enabled.
  ✔ Verify if Tiller Role Binding exist
  ↓ Create Tiller Role Binding [skipped]
    → Tiller Role Binding already exist.
  ✔ Verify if Tiller Service Account exists
  ↓ Create Tiller Service Account [skipped]
    → Tiller Service Account already exist.
  ✔ Create Tiller RBAC
  ✔ Verify if Tiller service exist
  ↓ Create Tiller Service [skipped]
    → Tiller Service already exist.
  ✔ Verify if namespace kube-che exist...It doesn't.
  ↓ Verify if Che server is already running [skipped]
    → Che namespace doesn't exist.
  ✔ Deploy Che Server
  ✔ Waiting for Che Server to start and respond
  ✔ Retrieving Che Server URL...http://che-kube-che.192.168.99.100.nip.io
```

**Comment by l0rd** [comment] 2019-02-06 21:04
Ok so first you hit a `minikube start` problem. Then you hit #27. 

`minikube start` is fragile. The errors you have faced are common ones. I have to reset it often as well. And it should not be `chectl` responsibility to start it successfully so I have created #20.

For #27 I was not able to reproduce it on Mac and Linux last week so was not able to understand why `helm init` fail from times to times. We need to investigate more on that one.

Anyway I am closing this issue since both problems are already tracked.

**Closed by l0rd** 2019-02-06 21:04 UTC
