### ISSUE TITLE
Che installation failure

### ISSUE THREAD

**Issue by garagatyi** [che-incubator/chectl#52] opened 2019-03-07 10:38 UTC
Che installation fails with:
<details>

```
✔  12:31 ~/workspace $ chectl server:start
  ✔ Platform preflight checklist (minikube) ✈️
    ✔ Verify if kubectl is installed
    ✔ Verify if minikube is installed
    ✔ Verify if minikube is running
    ✔ Start minikube
    ✔ Verify if minikube ingress addon is enabled
    ↓ Enable minikube ingress addon [skipped]
      → Ingress addon is already enabled.
    ✔ Retrieving minikube IP and domain for ingress URLs...192.168.99.101.nip.io.
  ❯ Running the installer (Helm) 🏎️
    ✔ Verify if helm is installed
    ✔ Create Tiller Role Binding...done.
    ✔ Create Tiller Service Account...done.
    ✔ Create Tiller RBAC
    ✔ Create Tiller Service...done.
    ✔ Preparing Che Helm Chart...done.
    ✔ Updating Helm Chart dependencies...done.
    ✖ Deploying Che Helm Chart
      → Error: "che" has no deployed releases
Error: Command failed: /bin/sh -c helm upgrade /
                            --install che /
                            --namespace kube-che /
                            --set global.ingressDomain=192.168.99.101.nip.io /
                            --set cheImage=eclipse/che-server:nightly /
                            --set global.cheWorkspacesNamespace=kube-che /
                              /home/gaal/.cache/chectl/templates/kubernetes/helm/che/
Error: UPGRADE FAILED: "che" has no deployed releases
UPGRADE FAILED
ROLLING BACK
Error: "che" has no deployed releases
    at makeError (/snapshot/chectl/node_modules/execa/index.js:174:9)
    at module.exports.Promise.all.then.arr (/snapshot/chectl/node_modules/execa/index.js:278:16)

```
</details>

**Comment by garagatyi** [comment] 2019-03-07 10:41
It seems that the reason is that chectl is called not from Che deploy/kubernetes/helm folder, but error doesn't say anything meaningful about it

**Comment by benoitf** [comment] 2019-03-07 10:42
hello, which chectl version are you using ?

also what is the helm version ?

**Comment by garagatyi** [comment] 2019-03-07 11:11
$ chectl version
chectl/0.0.2 linux-x64 node-v10.4.1
$ helm version
Client: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}

**Comment by l0rd** [comment] 2019-03-12 10:51
Closing as it is a duplicate of #18 where I have added more details (and how to fix it if someone is to keen enough to provide a PR :-)).

**Closed by l0rd** 2019-03-12 10:51 UTC
